import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import ClassReportContent from '@/components/printable-report/ClassReportContent';
import StudentReportContent from '@/components/printable-report/StudentReportContent';
import { institution } from '@/config/institution';
import { formatLocalDate } from '@/lib/date';
import { buildClassReport, buildStudentReport } from '@/lib/report';
import type { ReportPeriod } from '@/lib/report';
import { useDemoStore } from '@/store/useDemoStore';

const describePeriod = ({ start, end }: ReportPeriod): string => {
  if (!start && !end) return 'todo o período registrado';
  if (start && end) return `de ${formatLocalDate(start)} a ${formatLocalDate(end)}`;
  return start ? `a partir de ${formatLocalDate(start)}` : `até ${formatLocalDate(end)}`;
};

/**
 * Report built from the demo store and printed by the browser (`window.print()`),
 * whose print dialog also saves as PDF. No file is generated by the application.
 */
const PrintableReport = () => {
  const [searchParams] = useSearchParams();
  const { state } = useDemoStore();
  const [generatedAt] = useState(() => new Date());

  const kind = searchParams.get('kind');
  const period: ReportPeriod = { start: searchParams.get('from') ?? '', end: searchParams.get('to') ?? '' };
  const studentReport = kind === 'student' ? buildStudentReport(state, searchParams.get('student') ?? '', period) : null;
  const classReport = kind === 'class' ? buildClassReport(state, searchParams.get('class') ?? '', period) : null;

  if (!studentReport && !classReport) {
    return (
      <div className="container mx-auto max-w-3xl space-y-4 p-6">
        <h1 className="text-2xl font-bold">Relatório não encontrado</h1>
        <p className="text-muted-foreground">
          O estudante ou a turma do relatório não existem nos dados deste navegador. Gere o relatório de novo pelo
          Dashboard.
        </p>
        <Button asChild variant="outline">
          <Link to="/">Voltar ao Dashboard</Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="report-page container mx-auto max-w-4xl space-y-6 p-6 print:max-w-none print:p-0">
      <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <Button asChild variant="outline">
          <Link to="/">
            <ArrowLeft className="mr-2 h-4 w-4" aria-hidden="true" />
            Voltar ao Dashboard
          </Link>
        </Button>
        <Button onClick={() => window.print()}>
          <Printer className="mr-2 h-4 w-4" aria-hidden="true" />
          Imprimir ou salvar como PDF
        </Button>
      </div>

      <header className="space-y-1 border-b pb-4">
        <p className="text-sm text-muted-foreground">{institution.name}</p>
        <h1 className="text-2xl font-bold">
          {studentReport ? 'Relatório individual do estudante' : 'Relatório da turma'}
        </h1>
        <p className="text-lg font-medium">{studentReport ? studentReport.student.nomeCompleto : classReport?.label}</p>
        <p className="text-sm text-muted-foreground">
          Período: {describePeriod(period)}. Gerado em {generatedAt.toLocaleString(institution.locale)}.
        </p>
        <p className="text-sm">
          Dados de demonstração: registros fictícios ou cadastrados neste navegador. Não use este relatório com dados
          reais de estudantes.
        </p>
      </header>

      {studentReport && <StudentReportContent report={studentReport} />}
      {classReport && <ClassReportContent report={classReport} />}
    </div>
  );
};

export default PrintableReport;
